// Code generated by sqlc. DO NOT EDIT.

package sqlc

import ()

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Users0 struct {
}

type Users1 struct {
}
